package com.waectr.wetec.dataobject;

import java.util.Date;

public class ArticleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_like
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private Integer articleLike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_first_pic
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private String articleFirstPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_status
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private Integer articleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_title
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private String articleTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_user_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private Integer articleUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_publc_time
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private Date articlePublcTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.tag_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_article.article_context
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    private String articleContext;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_id
     *
     * @return the value of t_article.article_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_id
     *
     * @param articleId the value for t_article.article_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_like
     *
     * @return the value of t_article.article_like
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public Integer getArticleLike() {
        return articleLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_like
     *
     * @param articleLike the value for t_article.article_like
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setArticleLike(Integer articleLike) {
        this.articleLike = articleLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_first_pic
     *
     * @return the value of t_article.article_first_pic
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public String getArticleFirstPic() {
        return articleFirstPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_first_pic
     *
     * @param articleFirstPic the value for t_article.article_first_pic
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setArticleFirstPic(String articleFirstPic) {
        this.articleFirstPic = articleFirstPic == null ? null : articleFirstPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_status
     *
     * @return the value of t_article.article_status
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public Integer getArticleStatus() {
        return articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_status
     *
     * @param articleStatus the value for t_article.article_status
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setArticleStatus(Integer articleStatus) {
        this.articleStatus = articleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_title
     *
     * @return the value of t_article.article_title
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public String getArticleTitle() {
        return articleTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_title
     *
     * @param articleTitle the value for t_article.article_title
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setArticleTitle(String articleTitle) {
        this.articleTitle = articleTitle == null ? null : articleTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_user_id
     *
     * @return the value of t_article.article_user_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public Integer getArticleUserId() {
        return articleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_user_id
     *
     * @param articleUserId the value for t_article.article_user_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setArticleUserId(Integer articleUserId) {
        this.articleUserId = articleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_publc_time
     *
     * @return the value of t_article.article_publc_time
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public Date getArticlePublcTime() {
        return articlePublcTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_publc_time
     *
     * @param articlePublcTime the value for t_article.article_publc_time
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setArticlePublcTime(Date articlePublcTime) {
        this.articlePublcTime = articlePublcTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.tag_id
     *
     * @return the value of t_article.tag_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.tag_id
     *
     * @param tagId the value for t_article.tag_id
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_article.article_context
     *
     * @return the value of t_article.article_context
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public String getArticleContext() {
        return articleContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_article.article_context
     *
     * @param articleContext the value for t_article.article_context
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    public void setArticleContext(String articleContext) {
        this.articleContext = articleContext == null ? null : articleContext.trim();
    }
}