package com.waectr.wetec.dao;

import com.waectr.wetec.dataobject.ArticleDO;

public interface ArticleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    int deleteByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    int insert(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    int insertSelective(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    ArticleDO selectByPrimaryKey(Integer articleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    int updateByPrimaryKeySelective(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ArticleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_article
     *
     * @mbg.generated Mon May 25 14:17:51 CST 2020
     */
    int updateByPrimaryKey(ArticleDO record);
}